---
- name: Update packages and store count in a file
  hosts:
    -  linux_servers
  become: yes
  tasks:
    - name: Update packages using yum
      yum:
        name: "*"
        state: latest
      register: yum_update

    - name: Debug output of yum_update
      debug : 
            var: yum_update

    - name: Set fact for updated package count
      set_fact:
               updated_count: "{{ (yum_update.results | map(attribute='changed') | list | count) | int }}"
    - name: Collect updated counts
      set_fact:
                  updated_counts: "{{ updated_counts | default({}) | combine({inventory_hostname: updated_count}) }}"
      run_once: false
    - name: Remove the output file if it exists
      file:
            path: updated_package_counts.csv
            state: absent
      delegate_to: localhost  # Ensure this runs on the control machine
    - name: Create output file
      lineinfile:
        path: updated_package_counts.csv
        line: "hostname ,updated_package_count "
        create: yes
        state: present
      delegate_to: localhost  # Write to the file on the control machine
      run_once: true  # Ensure this task runs only once

    - name: Append count for each host to the output file
      lineinfile:
        path: updated_package_counts.csv
        line: "{{ inventory_hostname }}: {{ updated_count }} package updated"
        create: yes
        state: present
      delegate_to: localhost 
      when : updated_count | int  > 0  # Write to the file on the control machine

    - name: Check if updated_count is 0 and write second last line of yum command output
      lineinfile:
        path: updated_package_counts.csv
        line: "{{ inventory_hostname }} : {{ yum_update.msg }} " #if yum_update < 1 else yum_update.result }}"
        create: yes
        state: present
      when: updated_count | int == 0 
      delegate_to: localhost 
